### ISSUE TITLE
v1.3.1 requires Ruby >= 2.0, breaks Jekyll install on at least ubuntu 14.04

### ISSUE THREAD

**Issue by emichael** [jekyll/jekyll-gist#13]
If you're going to require ruby 2.0, then you should increment your major version number as well. It's a backwards compatibility breaking change, especially since Jekyll depends on jekyll-gist ~> 1.0

**Comment by emichael** [comment]
Example of broken install: https://travis-ci.org/emichael/emichael.github.io/builds/75847543

**Comment by parkr** [comment]
Hey @emichael, I'll work on this. Jekyll 3.0 requires Ruby 2 or greater and 1.9.3 is EOL so you really should upgrade. That said, a promise is a promise.

**Comment by emichael** [comment]
It's not just me. It's everyone whose on ubuntu <= 14.04 (the latest LTS version).

The fix should be quite simple. Just yank this release from the RubyGems and re-release it as 2.0.

**Comment by ac-pevans** [comment]
This is an issue on CircleCI as well; by default, the only Ruby version you get is 1.9.3. A workaround is to install ruby2.0 and ruby2.0-dev via apt-get, then use gem2.0 to install jekyll.

**Comment by emichael** [comment]
@ac-pevans Right, there are workarounds. You could always install jekyll-gist -v 1.3.0 then jekyll or install Ruby 2. This shouldn't be an issue at all, though.

**Comment by parkr** [comment]
Yanked. https://rubygems.org/gems/jekyll-gist/versions

Working in #14 on a 1.3.2 that keeps 1.9.3 support.

**Comment by gr4y** [comment]
*sighs* with a twitching eye.

@ac-pevans: I recommend [ruby-install](https://github.com/postmodern/ruby-install) for easily installing ruby versions and [chruby](github.com/postmodern/chruby) for switching. I won't recommend rvm, because it got really bloaty.

**Comment by emichael** [comment]
@parkr :+1:

**Comment by ac-pevans** [comment]
Thanks for the recommendation, @gr4y.

**Comment by gr4y** [comment]
@ac-pevans You are very much welcome. I am using Debian Wheezy myself and when I have installed it, the most recent version of ruby was 1.8, which already was EOL for about 12 months.
