### ISSUE TITLE
Installation problem - Ruby version >= 2.0

### ISSUE THREAD

**Issue by mykagrove** [jekyll/jekyll-gist#15]
I'm getting into a right pickle here trying to get jekyll gems running in general, not sure what's causing the problem so my apologies if this is the wrong place to start asking for help.

Here is my gemfile, following by the commands I've tried:
```
source 'https://rubygems.org'
gem 'jekyll'
```

```
$ bundle update
Fetching gem metadata from http://rubygems.org/...........
Fetching version metadata from http://rubygems.org/...
Fetching dependency metadata from http://rubygems.org/..
Resolving dependencies...
Using blankslate 2.1.2.4
Using hitimes 1.2.2
Using timers 4.0.1
Using celluloid 0.16.1
Using fast-stemmer 1.0.2
Using classifier-reborn 2.0.3
Using coffee-script-source 1.9.1.1
Using execjs 2.6.0
Using coffee-script 2.4.1
Using colorator 0.1
Using ffi 1.9.10
Using jekyll-coffeescript 1.0.1
Installing jekyll-gist 1.3.2 (was 1.3.0)

Gem::InstallError: jekyll-gist requires Ruby version >= 2.0.
An error occurred while installing jekyll-gist (1.3.2), and Bundler cannot
continue.
Make sure that `gem install jekyll-gist -v '1.3.2'` succeeds before bundling.
```

I'm on Ubuntu 14.04 which had Ruby 1.9.3 (the apt-get version), which I painstakingly updated to version 2.1 as you can see:
```
$ ruby --version
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux-gnu]
```

And the thing that really confusing is that it installs okay individually
```
$ sudo gem install jekyll-gist -v '1.3.2'
Successfully installed jekyll-gist-1.3.2
Parsing documentation for jekyll-gist-1.3.2
Done installing documentation for jekyll-gist after 0 seconds
1 gem installed
```

But then if I run bundle update again, it fails in the same way as before.

**Comment by mykagrove** [comment]
Update! I've brutally removed and updated ruby to 2.2 and reinstalled jekyll, etc from scratch which seems to have helped! 
Here are my commands and any relevant output:
```
$ sudo apt-get remove ruby2.1* ruby1.9.1 libruby1.9.1
$ sudo apt-get autoremove
$ sudo apt-add-repository ppa:brightbox/ruby-ng
$ sudo apt-get update
$ sudo apt-get install ruby2.2
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux-gnu]
$ sudo gem install jekyll
$ sudo gem install bundler
$ bundler update
```

Hope this is useful to anyone with a similar problem!

**Comment by gr4y** [comment]
I think @parkr should have released a new version of jekyll-gist which fixes the cause of that issue. (See #14 and #13 for more information)

I myself wouldn't rely heavily on the APT package sources when it comes to ruby, because you will get 1.9.3, which hit its end of life on February 23rd, 2015. I would recommend [ruby-install](https://github.com/postmodern/ruby-install) just for installing more recent versions of ruby. (There are other tools like rvm and rbenv, but they do to much in my opinion.)
