### ISSUE TITLE
noscript fallback solution slows down site generation

### ISSUE THREAD

**Issue by tiagoamaro** [jekyll/jekyll-gist#17]
Hi,

First, thanks a lot for this Jekyll core extension :)

## Issue

After updating to version v1.3.1, I've noticed that generating static websites on my local machine were taking 5 sec to 20 sec. After rolling back to v1.2.1, my website took 0.1 sec to generate.

I started investigating, and found out that the new `noscript` fallback feature is to blame (https://github.com/jekyll/jekyll-gist/pull/7), since it depends on a connection, instead of handling everything locally.

I understand that this feature is desirable for RSS feeds and many public facing websites, but Jekyll's speed is one of its great features.

Is it interesting having an option where users could deactivate the `noscript` fallback? something like:

```liquid
{% gist user/1234567 foo.js noscript:false %}
```

**Comment by pathawks** [comment]
It seems like, if `noscript` is to be deactivated, it would be best to make it a sitewide option.

**Comment by parkr** [comment]
```text
gist:
  noscript: false
```

?

**Comment by pathawks** [comment]
Seems reasonable to me.

**Comment by parkr** [comment]
There isn't a solution I really like in this case. On one hand, the HTML is true. On the other, it becomes slow by default. Jekyll 3 won't have this issue because jekyll-gist won't be bundled by default.

@benbalter: any thoughts here?
