### ISSUE TITLE
The noscript tag generates encoding error within Liquid

### ISSUE THREAD

**Issue by gergelypolonkai** [jekyll/jekyll-gist#18]
When I insert one of my gists with Unicode characters in it (e.g. [this one](https://gist.githubusercontent.com/gergelypolonkai/498a32297f39b4960ad7/raw/555c8802a5d694c572643ceb7998c0a7b28e3c1b/helper.py)) I get a Liquid error:

    Liquid Exception: incompatible character encodings: UTF-8 and ASCII-8BIT

After a bit of debugging it turned out that the contents of the Gist is not encoded right, most probably because github itself doesn’t send a Content-Type header or any other means of specifying the encoding of the raw Gist.

**Comment by parkr** [comment]
Could easily be a problem with HTTP::Response's `body` encoding.

**Comment by gr4y** [comment]
`response.body.encoding` is ASCII-8BIT. I don't know if it is a smart idea to do an `force_encoding('UTF-8')` on `response.body`. Any opinions, guys?

**Comment by gergelypolonkai** [comment]
The gist I provided as an example contains an apostrophe, e.g. in "don't"
in one of the comments (check it on the web version). If that is valid UTF8
(it should be), I think we can safely assume that downloaded gists are in
UTF-8. The root cause in this case, I assume, is that Github doesn't send
an encoding with the response (hence the ASCII-8BIT instead of any other
value). It may worth a bug report towards GH, although I'm not sure this is
actually a bug (I mean, gists can be uploaded with git-push, so they may be
in any esoteric encoding).

On the other hand (and I'm talking as a total noob here, never ever
touching Ruby code before, except debugging this particular case), isn't it
possible to add a config parameter or such to disable <noscript> generating?
