### ISSUE TITLE
Replace gist id string with a variable

### ISSUE THREAD

**Issue by coalwater** [jekyll/jekyll-gist#2]
Is there a way i could replace the normal string gist id with a variable i have in my post that holds the gist id for example?  
I tried these two following formats but both ended up being added as a literal string, is there a way to force it to be evaluated first?

    ----
    gist_id: 123456789
    ----

    {% gist gist_id file.ext %}
    {% gist {{gist_id}} file.ext %}

**Comment by parkr** [comment]
Interesting idea! What's the use case for this? In what situations would you need to do this?

**Comment by coalwater** [comment]
I use gists for my code snippets in my articles, I end up having to copy and paste the gist call in each line and replace the file name, I thought maybe I could add the gist_id as a variable in the post at the top then call it in all my gist calls in the article.

**Comment by coalwater** [comment]
Now that I think of it, it's more interesting to eliminate the need of adding `gist_id` in each gist call if I set the `gist_id` it at the top of my post, don't know if that's possible or not, I could try testing it and create a pull request

**Comment by parkr** [comment]
This would be pretty simple to implement. Feel free to give it a shot – I won't have time for a little while.

**Comment by coalwater** [comment]
I already did, but all the specs are done on the gist string directly, don't know yet how to pass an actual post to the spec to test the output, any references you can guide me to ?

**Comment by parkr** [comment]
here's something from the main jekyll repo: https://github.com/jekyll/jekyll/blob/master/test/test_tags.rb#L7-L21

**Comment by coalwater** [comment]
Thanks I'll take a look, btw I got it working and i tested it on my blog locally, I just need to add the spec then I'll create the pr

**Comment by parkr** [comment]
@coalwater sounds good! feel free to put up the pr earlier if you want feedback or help :)
