### ISSUE TITLE
Add 'async' to Javascript tag

### ISSUE THREAD

**Issue by ChuckMac** [jekyll/jekyll-gist#25]
I could be wrong, but I would think most people would want the gist's to load asynchronously and not stop page render.  

`<script src="http://gist.github.com/xxx.js" async></script>`

**Comment by pathawks** [comment]
Scripts that are loaded asynchronously [cannot call `document.write()`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#Browser_compatibility).

The **gist** embed script calls `document.write()`

The **gist** embed script cannot be called asynchronously.

**Comment by parkr** [comment]
Thanks, @pathawks!

**Comment by ChuckMac** [comment]
Thanks for the explanation @pathawks, TIL
