### ISSUE TITLE
Line highlighting in code blocks

### ISSUE THREAD

**Issue by Aallam** [jekyll/jekyll-gist#33]
Hello,

I wonder if it is possible to add lines highlighting ?

Thanks

**Comment by parkr** [comment]
@Aallam Hey! What do you mean? The gists automatically have highlighting and line numbers, I believe.

**Comment by Aallam** [comment]
@parkr 
Example: https://gist.github.com/Aallam/f947bc81c6be0a2045d0a0e61441afe5#file-postrm-L8-L14
(see the lines highlighting here from L8 to L14)

**Comment by parkr** [comment]
Ohhh, you mean highlighting of the lines, not syntax highlighting.

This is certainly possible. @imathis built this for octopress as [the `mark` parameter to code blocks](http://octopress.org/docs/blogging/code/). That said, it's not a feature that 80% of our users will find useful so I am going to close this as a feature request.

If you want to submit a PR to add it to our `highlight` tag, I'll gladly take a look – just not a necessity for us.

Thanks!
