### ISSUE TITLE
bug: undefined method `has_key?' after upgrading to Jekyll 3.5

### ISSUE THREAD

**Issue by marcanuy** [jekyll/jekyll-gist#42]
~~~
$ jekyll serve --trace 
NoMethodError: undefined method `has_key?' for #<Liquid::Context:0x0055e25ad300f8>                                                      
  /var/lib/gems/2.3.0/gems/jekyll-gist-1.4.0/lib/jekyll-gist/gist_tag.rb:17:in `render'
  ...
~~~

In Liquid 4.0 [has_key has been renamed to key](https://github.com/Shopify/liquid/commit/5919626da428995c247e1696f979a36e91f330d0)

Fixed in #41

**Comment by DirtyF** [comment]
Same here, this bug prevents from using Jekyll 3.5 for now as deploy fails 😢 

> Generating...
3:57:55 PM: Liquid Exception: undefined method `has_key?' for #<Liquid::Context:0x0000000478d648> in /opt/build/repo/_posts/2016-09-18-utiliser-des-plugins-jekyll-avec-github-pages.md
3:57:55 PM: jekyll 3.5.0 | Error: undefined method `has_key?' for #<Liquid::Context:0x0000000478d648>

**Comment by parkr** [comment]
v1.4.1 was just released!
