### ISSUE TITLE
Remove incorrect version for octokit

### ISSUE THREAD

**Issue by utkarsh2102** [jekyll/jekyll-gist#69]
Hey,

I don't think octokit 4.2 will work with for the test.
There's 4.13 out now. Could you please patch the same?

https://github.com/jekyll/jekyll-gist/blob/ca86372c3e5d9a64911e426adf3d4d8836f2da57/jekyll-gist.gemspec#L24

Or I can send a PR for the same?

**Comment by utkarsh2102** [comment]
Or can it be `>=4.2`?

**Comment by ashmaroli** [comment]
@utkarsh2102 `4.13` is not a subset of `4.1`.
`"~> 4.2"` means any version between `4.2.0` and `5.0.0`
