### ISSUE TITLE
Are there any style customization support, or out of the box themes available?

### ISSUE THREAD

**Issue by eriknelson** [jekyll/jekyll-gist#83]
I've been experimenting with the `minima` dark theme from their master branch, but one of the pain points is that with a dark theme, the embedded gists look like a mess:

![image](https://user-images.githubusercontent.com/410933/90749480-7d6b0880-e2a1-11ea-915a-4fff472cc19a.png)

What kind of options are there available to customize this, if any at all?

**Comment by ashmaroli** [comment]
@eriknelson Thank you for bring this issue to our notice.
Technically, the presentation aspect is outside the scope of this plugin and should be handled by the theme itself.

Will you be able to submit a PR to Minima directly?

**Comment by eriknelson** [comment]
>  Technically, the presentation aspect is outside the scope of this plugin and should be handled by the theme itself.

That's a fair point, I will file an issue with minima and see if they can point me in the right direction to submit a PR. Thanks for the quick response.
